### ISSUE TITLE
mpirun or mpiexec?

### ISSUE THREAD

**Issue by nazirahmk** [sc3260s18/MPI#1]
Hi,

I'm just wondering, when running in accre, which one is the best to use? I tried mpirun but it turns out some error like this.. 

└─>$ mpirun -n 2 ./mpi_hello

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 17418 RUNNING AT vmps09
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 17419 RUNNING AT vmps09
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================

and while using mpiexec, as mention in class, it will automatically do srun. But the output is correct.
└─>$ mpiexec -n 2 ./mpi_hello
srun: job 26304756 queued and waiting for resources
srun: job 26304756 has been allocated resources

Greetings from process 1 of 2, ready to receive messages!

Waiting on message from process 2 of 2...
Message generated from process 2 of 2, sending to process 1!

How do we run the mpi without sending a job on accre?

Thanks!!

**Comment by frenchwr** [comment]
Yeah, this is an annoying quirk about running MPI interactively in our environment (e.g. from a gateway or directly from one of the vmp90X nodes). You should use ```mpirun``` but only after unsetting the following environment variable: I_MPI_PMI_LIBRARY

You only have to do this once per login session. Do NOT put this in your ~/.bashrc, otherwise when you submit to SLURM the job will fail. You'll notice that I unset this variable in the simulate.sh script that I provided with homework 3 so you can run interactively from a gateway. To summarize:

```bash
unset I_MPI_PMI_LIBRARY
mpirun -n 2 ./mpi_hello
mpirun -n 4 ./mpi_goodbye
mpirun -n 8 ./mpi_back_to_studying
```

When I ran these examples in class, I was using ```mpiexec```, but as you noticed, this will actually be treated as a SLURM job, so if the cluster is busy the job may take awhile to run, which is not ideal for interactive prototyping and code development.

**Comment by nazirahmk** [comment]
I see, alright will do that. 

Yes, I saw that you used `mpiexec`, and did see the mpirun in bash script on homework 3.

Thanks @frenchwr !

**Comment by frenchwr** [comment]
No problemo! Happy studying.
